version: '3.4'

services:
  json-generator:
    build: ./docker/json-gen
    image: json-data-generator
    container_name: json-gen
    volumes:
      - ./docker/json-gen/logs:/json-data-generator/logs
      - ./docker/json-gen/conf:/json-data-generator/conf
    networks:
      - avro_poc_avro
    tty: true

  process-mgr:
    build:
      context: ./svc-process-mgr
      dockerfile: Dockerfile
    image: svc-process-mgr
    container_name: svc-process-mgr
    networks:
      - avro_poc_avro
    environment:
      - KAFKA_BROKER_URI=kafka:29092
      - LOAN_TOPIC_NAME=loan
      - PAYMENT_TOPIC_NAME=payment
      - SCHEMA_REGISTRY_URI=schema-registry-host:8081
    tty: true

  loan:
    build:
      context: ./svc-loan-io
      dockerfile: Dockerfile
    image: svc-loan-io
    container_name: svc-loan-io
    ports:
      - 8000:8080
    networks:
      - avro_poc_avro
    environment:
      - KAFKA_BROKER_URL=kafka:29092
      - SCHEMA_REGISTRY_URL=http://schema-registry-host:8081
      - LOAN_TOPIC_CONSUME=loan_intake
      - LOAN_TOPIC_PRODUCE=loan
      - PAYMENT_TOPIC_CONSUME=payment
      - PAYMENT_SERVICE_HOST=http://payment:3000
      - STATSD_SERVER_HOST=grafana.dev.enova.com
    tty: true

  payment:
    build:
      context: ./svc-payment
      dockerfile: Dockerfile
    image: svc-payment
    container_name: svc-payment
    networks:
      - avro_poc_avro
    ports:
      - 3000:3000
    environment:
      - KAFKA_BROKER_ADDR=kafka:29092
      - STATSD_SERVER=grafana.dev.enova.com:8125
    tty: true

networks:
  avro_poc_avro:
    external: true
