version: '3.4'

services:
  json-generator:
    build: ./docker/json-gen
    image: json-data-generator
    container_name: json-gen
    volumes:
      - ./docker/json-gen/logs:/json-data-generator/logs
      - ./docker/json-gen/conf:/json-data-generator/conf
    networks:
      - lss_poc_lss
    tty: true

  # process-mgr:
  #   build:
  #     context: ./svc-process-mgr
  #     dockerfile: Dockerfile
  #   image: svc-process-mgr
  #   container_name: svc-process-mgr
  #   depends_on:
  #     - kafka
  #   networks:
  #     - lss
  #   environment:
  #     - KAFKA_BROKER_URI=kafka:9092
  #     - TOPIC_NAME=intake
  #   tty: true
  #
  loan:
    build:
      context: ./svc-loan-io
      dockerfile: Dockerfile
    image: svc-loan
    container_name: svc-loan
    ports:
      - 8000:8080
    networks:
      - lss_poc_lss
    environment:
      - KAFKA_BROKER_HOST=kafka
      - SCHEMA_REGISTRY_HOST=schema-registry-host
    tty: true
  #
  # payment:
  #   build:
  #     context: ./svc-payment-io
  #     dockerfile: Dockerfile
  #   image: svc-loan
  #   container_name: svc-payment
  #   depends_on:
  #     - kafka
  #   ports:
  #     - 9000:8080
  #   networks:
  #     - lss
  #   environment:
  #     - KAFKA_BROKER_HOST=kafka
  #   tty: true

networks:
  lss_poc_lss:
    external: true
