version: '3.4'

services:
  json-generator:
    build: ./docker/json-gen
    image: json-data-generator
    container_name: json-gen
    volumes:
      - ./docker/json-gen/logs:/json-data-generator/logs
      - ./docker/json-gen/conf:/json-data-generator/conf
    networks:
      - lss_poc_lss
    tty: true

  process-mgr:
    build:
      context: ./svc-process-mgr
      dockerfile: Dockerfile
    image: svc-process-mgr
    container_name: svc-process-mgr
    networks:
      - lss_poc_lss
    environment:
      - KAFKA_BROKER_URI=kafka:29092
      - LOAN_TOPIC_NAME=loan
      - PAYMENT_TOPIC_NAME=payment
      - SCHEMA_REGISTRY_URI=schema-registry-host:8081
    tty: true

  loan:
    build:
      context: ./svc-loan-io
      dockerfile: Dockerfile
    image: svc-loan-io
    container_name: svc-loan-io
    ports:
      - 8000:8080
    networks:
      - lss_poc_lss
    environment:
      - KAFKA_BROKER_URL=kafka:29092
      - SCHEMA_REGISTRY_URL=http://schema-registry-host:8081
      - LOAN_TOPIC_CONSUME=loan_intake
      - LOAN_TOPIC_PRODUCE=loan
      - PAYMENT_TOPIC_CONSUME=payment
    tty: true

  # payment:
  #   build:
  #     context: ./svc-payment-io
  #     dockerfile: Dockerfile
  #   image: payment-svc
  #   container_name: payment-svc
  #   depends_on:
  #     - kafka
  #   ports:
  #     - 9000:8080
  #   networks:
  #     - lss
  #   environment:
  #     - KAFKA_BROKER_HOST=kafka
  #   tty: true

networks:
  lss_poc_lss:
    external: true
