// Code generated by github.com/actgardner/gogen-avro. DO NOT EDIT.
/*
 * SOURCE:
 *     loan.avsc
 */

package main

import (
	"io"
)

type Loan struct {

	// loan status
	Status                    string `avro:"status"`
	CalledDue                 bool   `avro:"calledDue"`
	DateClosed                string `avro:"dateClosed"`
	DateOpened                string `avro:"dateOpened"`
	LoanNumber                string `avro:"loanNumber"`
	DaysPastDue               int32  `avro:"daysPastDue"`
	CurrentOwner              string `avro:"currentOwner"`
	TransferFrom              string `avro:"transferFrom"`
	SourceAccountNumber       string `avro:"sourceAccountNumber"`
	AmountPastDueInCents      int32  `avro:"amountPastDueInCents"`
	CurrentBalanceInCents     int32  `avro:"currentBalanceInCents"`
	LastPaymentContingent     bool   `avro:"lastPaymentContingent"`
	TransferEffectiveDate     string `avro:"transferEffectiveDate"`
	CalledDueAmountInCents    int32  `avro:"calledDueAmountInCents"`
	OustandingBalanceCents    int32  `avro:"oustandingBalanceCents"`
	InCollectionBeforeClosed  bool   `avro:"inCollectionBeforeClosed"`
	OriginalLoanAmountInCents int32  `avro:"originalLoanAmountInCents"`
}

func DeserializeLoan(r io.Reader) (*Loan, error) {
	return readLoan(r)
}

func NewLoan() *Loan {
	v := &Loan{}
	v.Status = ""
	v.CalledDue = true
	v.DateClosed = ""
	v.DateOpened = ""
	v.LoanNumber = ""
	v.DaysPastDue = 0
	v.CurrentOwner = ""
	v.TransferFrom = ""
	v.SourceAccountNumber = ""
	v.AmountPastDueInCents = 0
	v.CurrentBalanceInCents = 0
	v.LastPaymentContingent = false
	v.TransferEffectiveDate = ""
	v.CalledDueAmountInCents = 0
	v.OustandingBalanceCents = 0
	v.InCollectionBeforeClosed = false
	v.OriginalLoanAmountInCents = 0

	return v
}

func (r *Loan) Schema() string {
	return "{\"fields\":[{\"default\":\"\",\"doc\":\"loan status\",\"name\":\"status\",\"type\":\"string\"},{\"default\":true,\"doc\":\"\",\"name\":\"calledDue\",\"type\":\"boolean\"},{\"default\":\"\",\"doc\":\"\",\"name\":\"dateClosed\",\"type\":\"string\"},{\"default\":\"\",\"doc\":\"\",\"name\":\"dateOpened\",\"type\":\"string\"},{\"default\":\"\",\"doc\":\"\",\"name\":\"loanNumber\",\"type\":\"string\"},{\"default\":0,\"doc\":\"\",\"name\":\"daysPastDue\",\"type\":\"int\"},{\"default\":\"\",\"doc\":\"\",\"name\":\"currentOwner\",\"type\":\"string\"},{\"default\":\"\",\"doc\":\"\",\"name\":\"transferFrom\",\"type\":\"string\"},{\"default\":\"\",\"doc\":\"\",\"name\":\"sourceAccountNumber\",\"type\":\"string\"},{\"default\":0,\"doc\":\"\",\"name\":\"amountPastDueInCents\",\"type\":\"int\"},{\"default\":0,\"doc\":\"\",\"name\":\"currentBalanceInCents\",\"type\":\"int\"},{\"default\":false,\"doc\":\"\",\"name\":\"lastPaymentContingent\",\"type\":\"boolean\"},{\"default\":\"\",\"doc\":\"\",\"name\":\"transferEffectiveDate\",\"type\":\"string\"},{\"default\":0,\"doc\":\"\",\"name\":\"calledDueAmountInCents\",\"type\":\"int\"},{\"default\":0,\"doc\":\"\",\"name\":\"oustandingBalanceCents\",\"type\":\"int\"},{\"default\":false,\"doc\":\"\",\"name\":\"inCollectionBeforeClosed\",\"type\":\"boolean\"},{\"default\":0,\"doc\":\"\",\"name\":\"originalLoanAmountInCents\",\"type\":\"int\"}],\"name\":\"Loan\",\"namespace\":\"com.lss.models\",\"type\":\"record\",\"version\":\"1\"}"
}

func (r *Loan) Serialize(w io.Writer) error {
	return writeLoan(r, w)
}
