// Code generated by github.com/actgardner/gogen-avro. DO NOT EDIT.
/*
 * SOURCES:
 *     payment.avsc
 *     payment_list.avsc
 *     loan.avsc
 */

package main

import (
	"io"
)

type Loan struct {
	LoanNumber          string
	SourceAccountNumber string
	CurrentOwner        string
}

func DeserializeLoan(r io.Reader) (*Loan, error) {
	return readLoan(r)
}

func NewLoan() *Loan {
	v := &Loan{}

	return v
}

func (r *Loan) Schema() string {
	return "{\"fields\":[{\"doc\":\"\",\"name\":\"loanNumber\",\"type\":\"string\"},{\"doc\":\"\",\"name\":\"sourceAccountNumber\",\"type\":\"string\"},{\"name\":\"currentOwner\",\"type\":\"string\"}],\"name\":\"Loan\",\"namespace\":\"com.lss.models\",\"type\":\"record\",\"version\":\"1\"}"
}

func (r *Loan) Serialize(w io.Writer) error {
	return writeLoan(r, w)
}
