// Code generated by github.com/actgardner/gogen-avro. DO NOT EDIT.
/*
 * SOURCES:
 *     payment_list.avsc
 *     loan.avsc
 */

package main

import (
	"io"
)

type Payment struct {
	Paid                   bool
	DatePaid               string
	LoanNumber             string
	AmountInCents          int32
	SourceAccountNumber    string
	SourcePaymentNumber    string
	SourceObligationNumber string
}

func DeserializePayment(r io.Reader) (*Payment, error) {
	return readPayment(r)
}

func NewPayment() *Payment {
	v := &Payment{}

	return v
}

func (r *Payment) Schema() string {
	return "{\"fields\":[{\"name\":\"paid\",\"type\":\"boolean\"},{\"name\":\"datePaid\",\"type\":\"string\"},{\"name\":\"loanNumber\",\"type\":\"string\"},{\"name\":\"amountInCents\",\"type\":\"int\"},{\"name\":\"sourceAccountNumber\",\"type\":\"string\"},{\"name\":\"sourcePaymentNumber\",\"type\":\"string\"},{\"name\":\"sourceObligationNumber\",\"type\":\"string\"}],\"name\":\"payment\",\"type\":\"record\"}"
}

func (r *Payment) Serialize(w io.Writer) error {
	return writePayment(r, w)
}
