spring:
  cloud:
    stream:
      bindings:
          contentType: application/*+avro
          destination: loan
      schemaRegistryClient:
        endpoint: http://localhost:8081
      schema:
        avro:
          schema-locations: classpath:avro/loan.avsc